# animal_facts.py

animal_facts = {
    "red_panda": "Es omnívoro, pero prefiere el bambú.",
    "tiger": "Puede dormir hasta 20 horas al día.",
    "penguin": "Las parejas suelen permanecer juntas de por vida.",
    "elephant": "Tiene la memoria más grande del reino animal.",
    "giraffe": "Solo duerme entre 10 y 20 minutos seguidos.",
    "koala": "Duerme hasta 22 horas al día.",
    "kangaroo": "No puede caminar hacia atrás.",
    "owl": "Puede girar su cabeza hasta 270 grados.",
    "dolphin": "Duerme con un ojo abierto.",
    "sloth": "Tarda un mes en digerir una hoja.",
    "lion": "Los rugidos se pueden oír hasta a 8 km.",
    "wolf": "Tiene un sentido del olfato 100 veces más agudo que el humano.",
    "bear": "Algunas especies hibernan hasta 7 meses.",
    "fox": "Sus orejas ayudan a disipar el calor.",
    "zebra": "Sus rayas son únicas, como huellas dactilares.",
    "cheetah": "Es el animal terrestre más rápido.",
    "camel": "Puede beber hasta 135 litros en una sola sesión.",
    "panda": "Comen hasta 12 horas al día para obtener suficiente bambú.",
    "rhino": "Su cuerno está hecho de keratina, como las uñas.",
    "hippopotamus": "Suda un líquido rojo que actúa como protector solar.",
    "flamingo": "Su color rosa viene de su dieta de camarones.",
    "parrot": "Algunos pueden aprender más de 100 palabras.",
    "snake": "Algunas pueden oler con la lengua.",
    "eagle": "Su visión es 4 a 8 veces más aguda que la humana.",
    "shark": "Pueden detectar una gota de sangre en el agua a kilómetros.",
    "frog": "Absorben agua a través de la piel, no beben.",
    "butterfly": "Saben dónde migrar con precisión desde el nacimiento.",
    "ant": "Pueden levantar 50 veces su peso.",
    "bee": "Comunican la ubicación del néctar bailando.",
    "bat": "Son los únicos mamíferos que pueden volar.",
    "whale": "Suelen cantar para comunicarse a kilómetros.",
    "octopus": "Tiene tres corazones y sangre azul.",
    "crab": "Algunas especies pueden caminar hacia los lados.",
    "lobster": "Pueden regenerar sus extremidades perdidas.",
    "jellyfish": "No tienen cerebro ni corazón.",
    "gorilla": "Usan herramientas para recolectar alimento.",
    "chimpanzee": "Pueden aprender lenguaje de señas básico.",
    "parakeet": "Son aves muy sociales y parlanchinas.",
    "goldfish": "Tienen una memoria de hasta 3 meses.",
    "hedgehog": "Se enrollan en bola para protegerse.",
    "meerkat": "Tienen 'guardianes' que alertan de peligro.",
    "otter": "Usan piedras para abrir conchas.",
    "platypus": "Ponen huevos, pero es mamífero.",
    "alligator": "Pueden vivir más de 50 años.",
    "armadillo": "Se enrollan para defenderse.",
    "beaver": "Construyen diques para crear su hogar.",
    "buffalo": "Son animales muy resistentes y sociales.",
    "chameleon": "Cambian de color para comunicarse o camuflarse.",
    "cobra": "Sacan la capucha cuando están amenazados.",
    "crow": "Son extremadamente inteligentes y usan herramientas.",
    "deer": "Los ciervos machos pierden y regeneran sus astas anualmente.",
    "dove": "Simbolizan la paz en muchas culturas.",
    "eagle_ray": "Pueden saltar fuera del agua hasta 2 metros.",
    "ferret": "Son muy curiosos y juguetones.",
    "gazelle": "Son capaces de saltos largos y rápidos para escapar.",
    "goose": "Vuelan en formación para ahorrar energía.",
    "grasshopper": "Sus patas traseras son muy potentes para saltar.",
    "hamster": "Almacenan comida en sus mejillas.",
    "heron": "Son pacientes cazadores, permanecen quietos mucho tiempo.",
    "hippo": "Pueden aguantar la respiración hasta 5 minutos bajo el agua.",
    "iguana": "Pueden desprender la cola para escapar de depredadores.",
    "jaguar": "Son excelentes nadadores y trepadores.",
    "kingfisher": "Pueden sumergirse rápido para atrapar peces.",
    "lemur": "Son exclusivos de Madagascar.",
    "lobster": "Pueden vivir más de 50 años.",
    "manta_ray": "Pueden planear por el agua a gran velocidad.",
    "moose": "Son los más grandes de la familia de ciervos.",
    "narwhal": "Su 'cuerno' es un colmillo alargado.",
    "newt": "Pueden regenerar extremidades perdidas.",
    "orangutan": "Son muy inteligentes y usan herramientas.",
    "otter": "Duermen tomados de la mano para no separarse.",
    "ox": "Son animales de carga muy resistentes.",
    "pufferfish": "Se inflan para ahuyentar a los depredadores.",
    "quail": "Son aves pequeñas pero muy rápidas.",
    "raccoon": "Tienen manos muy hábiles y son nocturnos.",
    "reindeer": "Ambos sexos tienen astas.",
    "salamander": "Son indicadores de un ambiente sano.",
    "seahorse": "Los machos llevan los huevos hasta que nacen.",
    "seal": "Son excelentes buceadores y nadadores.",
    "shrew": "Tienen un metabolismo muy rápido.",
    "skunk": "Usan su olor para defenderse.",
    "starfish": "Pueden regenerar brazos perdidos.",
    "swan": "Pueden nadar y volar grandes distancias.",
    "tapir": "Son animales prehistóricos que han cambiado poco.",
    "toucan": "Tienen picos grandes y coloridos para atraer pareja.",
    "turkey": "Son nativos de América del Norte.",
    "vulture": "Son importantes para limpiar cadáveres.",
    "wallaby": "Son parientes pequeños del canguro.",
    "walrus": "Usan sus colmillos para salir del agua.",
    "wombat": "Cavan madrigueras complejas para vivir.",
    "yak": "Son resistentes a las alturas y el frío.",
    "zebra": "Sus rayas confunden a los depredadores.",
    "albatross": "Pueden volar miles de kilómetros sin descansar.",
    "anaconda": "Son las serpientes más grandes del mundo.",
    "baboon": "Viven en grandes grupos sociales.",
    "badger": "Son animales muy territoriales.",
    "bison": "Fueron casi extinguidos en el siglo XIX.",
    "blackbird": "Son conocidos por su canto melodioso.",
    "bluejay": "Pueden imitar sonidos de otros animales.",
    "bobcat": "Son excelentes cazadores solitarios.",
    "buffalo": "Son animales muy resistentes y sociales.",
    "butterfly": "Pasan por una metamorfosis completa.",
    "camel": "Pueden sobrevivir sin agua por semanas.",
    "cardinal": "Son pájaros muy territoriales y coloridos.",
    "cat": "Tienen un sentido del oído muy agudo.",
    "caterpillar": "Se transforman en mariposas o polillas.",
    "cheetah": "Alcanza hasta 120 km/h en cortas distancias.",
    "chimpanzee": "Comparten el 98% de ADN con humanos.",
    "clam": "Filtran agua para alimentarse.",
    "cobra": "Su veneno puede ser mortal para otras especies.",
    "cockatoo": "Son aves muy inteligentes y sociables.",
    "condor": "Tienen la mayor envergadura entre aves terrestres.",
    "cormorant": "Se zambullen para pescar a gran profundidad.",
    "coyote": "Son muy adaptables a distintos ambientes.",
    "crab": "Cambian de caparazón para crecer.",
    "crane": "Bailan para atraer pareja.",
    "crow": "Son conocidos por su inteligencia y memoria.",
    "deer": "Son herbívoros con gran sentido del oído.",
    "dingo": "Son perros salvajes australianos.",
    "dog": "Son los mejores amigos del hombre.",
    "dolphin": "Se comunican con sonidos y silbidos.",
    "donkey": "Son animales muy resistentes y fuertes.",
    "dragonfly": "Tienen una vista de casi 360 grados.",
    "duck": "Son aves acuáticas muy adaptables.",
    "eagle": "Son cazadores con visión aguda.",
    "eel": "Pueden generar electricidad para defenderse.",
    "falcon": "Son las aves más rápidas en picada.",
    "flamingo": "Su color proviene de los carotenoides en su dieta.",
    "fox": "Son muy astutos y adaptables.",
    "frog": "Absorben agua a través de la piel.",
    "gazelle": "Son rápidas y ágiles para escapar de depredadores.",
    "gecko": "Pueden trepar superficies verticales gracias a sus patas.",
    "goat": "Son muy curiosos y resistentes.",
    "goldfish": "Pueden vivir más de 20 años en cautiverio.",
    "gorilla": "Son los primates más grandes.",
    "grasshopper": "Producen sonidos frotando sus patas.",
    "gull": "Son aves marinas muy inteligentes.",
    "hamster": "Guardan comida en sus mejillas.",
    "hare": "Son más grandes y tienen patas traseras más largas que los conejos.",
    "hedgehog": "Se enrollan para protegerse.",
    "heron": "Cazan peces en aguas poco profundas.",
    "hippopotamus": "Suden un líquido rojo que protege su piel.",
    "horse": "Son animales de gran velocidad y resistencia.",
    "hummingbird": "Son las únicas aves que pueden volar hacia atrás.",
    "hyena": "Tienen mandíbulas muy fuertes.",
    "ibis": "Son aves zancudas que viven cerca del agua.",
    "jackal": "Son muy oportunistas y sociales.",
    "jellyfish": "Pueden ser inmortales en ciertas especies.",
    "kangaroo": "Saltan grandes distancias gracias a sus patas traseras.",
    "kingfisher": "Tienen picos afilados para atrapar peces.",
    "koala": "Comen hojas de eucalipto, que son tóxicas para otros animales.",
    "lemur": "Son exclusivos de Madagascar.",
    "leopard": "Son excelentes trepadores y cazadores nocturnos.",
    "lion": "Viven en grupos llamados manadas.",
    "lizard": "Pueden perder y regenerar la cola.",
    "llama": "Son animales de carga en los Andes.",
    "lobster": "Pueden regenerar sus extremidades.",
    "macaw": "Son aves muy coloridas y ruidosas.",
    "magpie": "Pueden imitar sonidos y aprender trucos.",
    "mole": "Viven bajo tierra y tienen un sentido del olfato muy desarrollado.",
    "monkey": "Son animales sociales e inteligentes.",
    "moose": "Son los ciervos más grandes.",
    "mouse": "Se reproducen rápidamente y son muy adaptables.",
    "narwhal": "Su colmillo es en realidad un diente largo y recto.",
    "newt": "Pueden regenerar extremidades y órganos.",
    "nightingale": "Son conocidos por su canto melodioso.",
    "octopus": "Tienen tres corazones y son muy inteligentes.",
    "ostrich": "Son las aves más grandes y no vuelan.",
    "otter": "Usan herramientas para abrir moluscos.",
    "owl": "Son cazadores nocturnos con visión excepcional.",
    "ox": "Son animales de carga fuertes y resistentes.",
    "panda": "Comen principalmente bambú.",
    "parrot": "Pueden imitar sonidos humanos.",
    "peacock": "Los machos despliegan plumas coloridas para atraer pareja.",
    "pelican": "Tienen bolsas grandes para almacenar pescado.",
    "penguin": "Son aves que no vuelan y nadan excelentemente.",
    "pig": "Son animales muy inteligentes y limpios.",
    "pigeon": "Se orientan muy bien y han sido usados en mensajería.",
    "polar_bear": "Tienen pelaje transparente y piel negra debajo.",
    "porcupine": "Usan sus púas para defenderse.",
    "rabbit": "Son animales muy rápidos y fértiles.",
    "raccoon": "Son nocturnos y tienen manos muy hábiles.",
    "rat": "Son inteligentes y muy adaptables.",
    "reindeer": "Son esenciales para las culturas árticas.",
    "rhinoceros": "Tienen piel muy gruesa y cuernos resistentes.",
    "robin": "Son conocidos por su canto al amanecer.",
    "seal": "Son excelentes nadadores y pueden aguantar la respiración mucho tiempo.",
    "shark": "Tienen un sentido del olfato muy desarrollado.",
    "sheep": "Son animales sociales y dóciles.",
    "skunk": "Defienden con un olor muy fuerte.",
    "sloth": "Son los mamíferos más lentos.",
    "snail": "Se mueven lentamente usando un músculo ondulante.",
    "snake": "Algunas son venenosas y otras constrictoras.",
    "sparrow": "Son aves pequeñas y muy comunes.",
    "spider": "Producen seda para construir sus telarañas.",
    "squirrel": "Guardan comida para el invierno.",
    "starfish": "Pueden regenerar sus brazos.",
    "stork": "Son aves migratorias que cuidan a sus crías.",
    "swan": "Son símbolos de belleza y gracia.",
    "tapir": "Son animales solitarios y nocturnos.",
    "tiger": "Son los felinos más grandes.",
    "toad": "Tienen piel más rugosa que las ranas.",
    "toucan": "Tienen picos grandes y coloridos.",
    "turtle": "Pueden vivir más de 100 años.",
    "vulture": "Son carroñeros esenciales para el ecosistema.",
    "wallaby": "Son parientes pequeños de los canguros.",
    "walrus": "Usan sus colmillos para ayudarse a salir del agua.",
    "wasp": "Son importantes polinizadores y controladores de plagas.",
    "weasel": "Son cazadores ágiles y pequeños.",
    "whale": "Son los animales más grandes del planeta.",
    "wolf": "Viven y cazan en manadas.",
    "wombat": "Cavan madrigueras para vivir.",
    "yak": "Son resistentes al frío extremo.",
    "zebra": "Sus rayas ayudan a confundir a los depredadores."
}
